export const SEARCH_QUERY_ACTION = 'SEARCH_QUERY_ACTION';
export const MOVIES_RADIO_ACTION = 'MOVIES_RADIO_ACTION';
export const PEOPLE_RADIO_ACTION = 'PEOPLE_RADIO_ACTION';
export const SEARCH_RESULTS_ACTION = 'SEARCH_RESULTS_ACTION';
export const SELECTED_RESULT_ACTION = 'SELECTED_RESULT_ACTION';
export const SWAP_TO_MOVIE_ACTION = 'SWAP_TO_MOVIE_ACTION';