export const SEARCH_QUERY_ACTION = 'SEARCH_QUERY_ACTION';
export const MOVIES_RADIO_ACTION = 'MOVIES_RADIO_ACTION';
export const PEOPLE_RADIO_ACTION = 'PEOPLE_RADIO_ACTION';
export const SEARCH_RESULTS_ACTION = 'SEARCH_RESULTS_ACTION';